version: '3.7'

services:
  web:
    build: .
    command: python /product_exp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/product_exp
    ports:
      - 8000:8000
    env_file:
      - .env